### ISSUE TITLE
UnicodeEncodeErrors in report creation with pytest-html 3.2.0

### ISSUE THREAD

**Issue by robsan00** [pytest-dev/pytest-html#559]
Consider the following simple dummy test module:
```python
import logging

def test_spam():
    log = logging.getLogger("")
    log.critical("\x81")
```

Using a virtual environment with the following packets (which you get if you simply get pytest and pytest-html):
```
(pytest) C:\work\dev\venv>pip freeze
attrs==22.1.0
colorama==0.4.6
exceptiongroup==1.0.0
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.9
pytest==7.2.0
pytest-html==3.2.0
pytest-metadata==2.0.3
tomli==2.0.1
```

Triggering the tests will result in a UnicodeEncodeError:
```
(pytest) C:\work>pytest -v --html c:\work\test.html --self-contained-html pytest_html_error.py
================================================= test session starts =================================================
platform win32 -- Python 3.8.8, pytest-7.2.0, pluggy-1.0.0 -- C:\work\dev\venv\pytest\Scripts\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.8.8', 'Platform': 'Windows-10-10.0.19041-SP0', 'Packages': {'pytest': '7.2.0', 'pluggy': '1.0.0'}, 'Plugins': {'html': '3.2.0', 'metadata': '2.0.3'}}
rootdir: C:\work
plugins: html-3.2.0, metadata-2.0.3
collected 1 item

pytest_html_error.py::test_spam PASSED                                                                           [100%]Traceback (most recent call last):
  File "c:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\work\dev\venv\pytest\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\work\dev\venv\pytest\lib\site-packages\_pytest\config\__init__.py", line 190, in console_main
    code = main()
  File "C:\work\dev\venv\pytest\lib\site-packages\_pytest\config\__init__.py", line 167, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\work\dev\venv\pytest\lib\site-packages\_pytest\main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\work\dev\venv\pytest\lib\site-packages\_pytest\main.py", line 305, in wrap_session
    config.hook.pytest_sessionfinish(
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\work\dev\venv\pytest\lib\site-packages\_pytest\terminal.py", line 808, in pytest_sessionfinish
    outcome.get_result()
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\work\dev\venv\pytest\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\work\dev\venv\pytest\lib\site-packages\pytest_html\html_report.py", line 333, in pytest_sessionfinish
    self._save_report(report_content)
  File "C:\work\dev\venv\pytest\lib\site-packages\pytest_html\html_report.py", line 259, in _save_report
    self.logfile.write_text(report_content)
  File "c:\Python38\lib\pathlib.py", line 1255, in write_text
    return f.write(data)
  File "c:\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x81' in position 14220: character maps to <undefined>
```

When downgrading to pytest-html 3.1.1, the error disappears.

It's not just \x81 that leads to such problems, unicode characters also show this issue. This might be related to https://github.com/pytest-dev/pytest-html/issues/558 (though the error there is different).

**Comment by BeyondEvil** [comment]
Hopefully this is solved in the v4 release. which I hope is not too far away. I'm planning an RC release before EOW.

**Comment by elubs** [comment]
could this solve issue#100? it seems to be related. it looks as if test_id should be escaped

**Comment by KoMiI** [comment]
Its because of following change in html_record.py:259
```
        with open(self.logfile, "w", encoding="utf-8") as f:
            f.write(report_content)
---->
        self.logfile.write_text(report_content)
```

Someone who adds this patch forgot about to set encoding as it was. Function write_text have this param

**Comment by elubs** [comment]
I'm still getting UnicodeDecodeError after downgrade to 3.1.1

4, in __init__
    self.test_id = report.nodeid.encode("utf-8").decode("unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 168-169: malformed \N character escape

**Comment by elubs** [comment]
any way to go around it for now?

**Comment by jfthuong** [comment]
> any way to go around it for now?
> 

The easiest way is to stick to the previous version.

A more geeky (and not tested way) would be to patch the function using the line 259 by redefining the function with the correct implementation

**Comment by elubs** [comment]
previous versions resulted the same error for me

**Comment by jfthuong** [comment]
> previous versions resulted the same error for me
> 

Maybe you have a non ASCII test ID. Your problem might actually be different

**Comment by elubs** [comment]
> > previous versions resulted the same error for me
> 
> Maybe you have a non ASCII test ID. Your problem might actually be different

my test id is a windows path (destination:C:\Program Files (x86)\someprogram\ThirdParty\Npcap)) it fails on the '\N'.
The test itself passes as the input is escaped


    self.test_id = report.nodeid.encode("utf-8").decode("unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 168-169: malformed \N character escape

**Comment by jfthuong** [comment]
> C:\Program Files (x86)\someprogram\ThirdParty\Npcap

Yes, so it's definitely not a related issue.

Here is a simple way to reproduce your issue:

```python

import pytest

paths = ["C:\Program Files (x86)\someprogram\ThirdParty\Npcap"]

@pytest.mark.parametrize("path", paths)
def test(path):
    pass
```

Will raise this exception when trying to generate a HTML report:

```python
C:\AnsysDev\Python39\lib\ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "D:\AnsysDev\tfs_scripts\test_invalid.py", line 4
E       paths = ["C:\Program Files (x86)\someprogram\ThirdParty\Npcap"]
E                                                                     ^
E   SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 45-46: malformed \N character escape
```

But the exception disappears if you change the 4th line to:

```python
paths = [r"C:\Program Files (x86)\someprogram\ThirdParty\Npcap"]
```

Your "Windows path" is not a valid path: you should escape the `\` (either by using `\\` or putting inside a r-string like I did).

**Comment by jfthuong** [comment]
FYI: this is a temporary way to patch `pytest-html` to support non-ASCII characters.

The following code shall be executed during the test session: either putting inside a Test Case, in another file that is imported, or copy-paste in `conftest.py` (which ode is executed automatically during a test session).

```python

from pytest_html.html_report import HTMLReport

def _save_report_patched(self, report_content):
    dir_name = self.logfile.parent
    assets_dir = dir_name / "assets"

    dir_name.mkdir(parents=True, exist_ok=True)
    if not self.self_contained:
        assets_dir.mkdir(parents=True, exist_ok=True)

    self.logfile.write_text(report_content, encoding="utf-8")  # this file is modified 
    if not self.self_contained:
        style_path = assets_dir / "style.css"
        style_path.write_text(self.style_css)

HTMLReport._save_report = _save_report_patched

```

**Comment by SaturnIC** [comment]
> FYI: this is a temporary way to patch `pytest-html` to support non-ASCII characters.
> 
> The following code shall be executed during the test session: either putting inside a Test Case, in another file that is imported, or copy-paste in `conftest.py` (which is executed automatically during a test session).
> 
> ```python
> from pytest_html.html_report import HTMLReport
> 
> def _save_report_patched(self, report_content):
>     dir_name = self.logfile.parent
>     assets_dir = dir_name / "assets"
> 
>     dir_name.mkdir(parents=True, exist_ok=True)
>     if not self.self_contained:
>         assets_dir.mkdir(parents=True, exist_ok=True)
> 
>     self.logfile.write_text(report_content, encoding="utf-8")  # this line is modified 
>     if not self.self_contained:
>         style_path = assets_dir / "style.css"
>         style_path.write_text(self.style_css)
> 
> HTMLReport._save_report = _save_report_patched
> ```

Please merge this proposal

**Comment by SaturnIC** [comment]
> The bug is at in [pytest_html\html_report.py:259](https://github.com/pytest-dev/pytest-html/blob/master/src/pytest_html/html_report.py#L259)
> 
> ```python
>         self.logfile.write_text(report_content)
> ```
> 
> should be:
> 
> ```python
>         self.logfile.write_text(report_content, encoding="utf-8")
> ```
> 
> And this solves the problem

Please merge this.

**Comment by jfthuong** [comment]
> > The bug is at in [pytest_html\html_report.py:259](https://github.com/pytest-dev/pytest-html/blob/master/src/pytest_html/html_report.py#L259)
> > ```python
> >         self.logfile.write_text(report_content)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should be:
> > ```python
> >         self.logfile.write_text(report_content, encoding="utf-8")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And this solves the problem
> 
> Please merge this.

I don't know why I have not gotten that idea :) A patch is good for a moment but we need to help resolving the issue

**Comment by BeyondEvil** [comment]
Mind testing if this is still and issue in 4.0.0rc0?

**Comment by robsan00** [comment]
I can confirm that the issue as reported in the initial post is not present in 4.0.0rc0.
